// agent/main.go
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
)

// The incoming request from your React frontend
type PatientRequest struct {
	PatientContext string `json:"patientContext"`
}

func handleReasoning(w http.ResponseWriter, r *http.Request) {
	// Enable CORS for your React frontend
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type")
	if r.Method == "OPTIONS" {
		return
	}

	var reqData PatientRequest
	if err := json.NewDecoder(r.Body).Decode(&reqData); err != nil {
		http.Error(w, "Invalid request payload", http.StatusBadRequest)
		return
	}

	// Read the clean data generated by our ETL pipeline
	providersData, err := os.ReadFile("clean_providers.json")
	if err != nil {
		http.Error(w, "Provider data not found. Run ETL pipeline first.", http.StatusInternalServerError)
		return
	}

	systemPrompt := `You are an AI Clinical Triage Agent operating within the Four-Box Medical Ethics Model. 
You will be provided with a patient's context and a JSON array of available specialists.
Evaluate the specialists and return a JSON object with a 'matches' array containing the top 3 optimal specialists.
Each match MUST have:
1. "npi" (number)
2. "match_score" (number 0-100)
3. "medical_indications_justification" (string)
4. "justice_and_context_justification" (string) - explain how you factored in wait times, experience, and insurance.`

	promptContent := fmt.Sprintf("Patient Context: %s\n\nProviders: %s", reqData.PatientContext, string(providersData))

	// Call the LLM to process the matches
	llmResponse, err := callLLM(systemPrompt, promptContent)
	if err != nil {
		http.Error(w, "AI reasoning failed: "+err.Error(), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.Write(llmResponse)
}

func callLLM(systemPrompt, userPrompt string) ([]byte, error) {
	// Using OpenAI for strict JSON output support
	apiKey := os.Getenv("OPENAI_API_KEY")

	payload := map[string]interface{}{
		"model":           "gpt-4o",
		"response_format": map[string]string{"type": "json_object"},
		"messages": []map[string]string{
			{"role": "system", "content": systemPrompt},
			{"role": "user", "content": userPrompt},
		},
	}
	jsonPayload, _ := json.Marshal(payload)

	req, _ := http.NewRequest("POST", "https://api.openai.com/v1/chat/completions", bytes.NewBuffer(jsonPayload))
	req.Header.Set("Authorization", "Bearer "+apiKey)
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)

	// Extract just the JSON content from the OpenAI response
	var openAIResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	json.Unmarshal(body, &openAIResp)

	if len(openAIResp.Choices) == 0 {
		return nil, fmt.Errorf("empty response from LLM")
	}

	return []byte(openAIResp.Choices[0].Message.Content), nil
}

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	} // Fallback for local testing

	http.HandleFunc("/api/match", handleReasoning)

	fmt.Printf("Blaxel Go Agent running on port %s\n", port)
	log.Fatal(http.ListenAndServe(":"+port, nil))
}
